---
title: "Decision Quality and Uncertainty"
authors: "Prof. Mohammed A. Mohammed"
page-layout: article
---

# Speaker Bio

Professor Mohammed A Mohammed is an academic with extensive experience of applied health services research, including quality of care, patient safety and improvement science. Mohammed has 100+ peer reviewed publications, including landmark papers in the Lancet (on understanding variation in healthcare), BMJ (on bias in hospital mortality statistics), evaluation of a care bundle (JAMA Surgery) and a prize-winning study that developed an electronic frailty index for primary care (Age and Ageing). Mohammed led the development of the first primary care mortality monitoring system (BJGP) and was an expert witness to the Shipman Inquiry (BMJ). His current research projects include the development of automated risk equations for use in hospitals (BMJOpen). Mohammed has delivered scores of highly rated courses on variation, systems thinking, improvement science and mortality statistics to senior and front-line clinical staff in the NHS over the last ten years. Mohammed also founded the NHS-R community – which was written up as an exemplar case study for 21st Century data analytics in the NHS. Mohammed is currently working in the NHS as Head of Innovation & Academic Partnerships at the Strategy Unit. His main area of focus is innovative decision support systems. He is emeritus professor at the University of Bradford and Visiting Professor at Cardiff University.

# Summary of the Workshop

This workshop explores how to make high-quality decisions in complex and uncertain environments. Participants will learn the six elements of decision quality—clear objectives, meaningful alternatives, reliable information, sound reasoning, commitment to action, and alignment with values—and how these principles drive better outcomes. We will examine practical tools for assessing uncertainty and probabilistic thinking, to reduce risk and improve confidence in decision-making. Through interactive exercises and real-world examples, participants will gain insights enhacing decision quality and embracing uncertainty.

# Learning Outcomes

- **Understand the Six Elements of Decision Quality:** Participants will be able to identify and apply the core components—clear objectives, meaningful alternatives, reliable information, sound reasoning, alignment, and commitment—to improve decision-making effectiveness.

- **Analyze and Manage Uncertainty in Decision Processes:** Participants will learn practical techniques and probabilistic thinking to incorporate uncertainty into the decision making process.

# Structure of the session

This two hour interactive workshop will begin decision making and understanding the dimensions of high quality decision making and explore the role of uncertainty and how it can be incorporated to enhance decision quality.

# Prerequisites

- No prior knowledge is assumed
- Participants must have an interest in decision making

# Technical Requirements

Nothing outside standard options for a lecture room


# Pre-Work or Pre-Reading 


# Materials Provided to Participants

Slides

